export class Tool{
	constructor(){
		this.type="h1";
		this.lockClass=[];
		this.class="";
		this.text="";
		this.src="";
		this.module="test";
		this.placeholder="";
		this.content=[];
		this.editable=true;
		this.container=false;
		this.textOptions=false;
		this.spellcheck=null;
		this.alt="";
		this.canDrag=false;
		this.canRemove=true;
		this.canFocus=true;
		this.style="";
		this.href="";
		this.data={};
		this.attr={};
	}
}